### ISSUE TITLE
TypeError: as_view() takes exactly 1 argument (3 given)

### ISSUE THREAD

**Issue by fredericosachweh** [miki725/django-rest-framework-bulk#46]
Hi,
I'm use Django 1.9 and DRF3.
I tried follow the tutorial to create my ListBulkCreateUpdateDestroyAPIView.
I had problem to register the route.

I changed to BulkModelViewSet and fix my problem.

Can you help me to user ListBulkCreateUpdateDestroyAPIView?

**Comment by fredericosachweh** [comment]
+1

**Comment by miki725** [comment]
whats the traceback?

**Comment by fredericosachweh** [comment]
my traceback is a Title

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/helpers/pydev/pydevd.py", line 249, in __call__
    self.original_func(*self.args, **self.kwargs)
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/fredericomatos/projectos/smartgreen/smartgreen-panel/panel/urls.py", line 9, in <module>
    url(r'^screen/', include('screen.urls', namespace='screen'))
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/fredericomatos/projectos/smartgreen/smartgreen-panel/screen/urls.py", line 6, in <module>
    url(r'api/', include('screen.api.urls', namespace='api')),
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/fredericomatos/projectos/smartgreen/smartgreen-panel/screen/api/urls.py", line 6, in <module>
    url(r'', include('screen.api.v1.urls', namespace='default')),
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/fredericomatos/projectos/smartgreen/smartgreen-panel/screen/api/v1/urls.py", line 16, in <module>
    url(r'', include(router.urls))
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/rest_framework/routers.py", line 79, in urls
    self._urls = self.get_urls()
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/rest_framework/routers.py", line 317, in get_urls
    default_urls = super(DefaultRouter, self).get_urls()
  File "/Users/fredericomatos/ENVS/dash/lib/python2.7/site-packages/rest_framework/routers.py", line 256, in get_urls
    view = viewset.as_view(mapping, **route.initkwargs)
TypeError: as_view() takes exactly 1 argument (3 given)
```

**Comment by miki725** [comment]
how are you using your router?

**Comment by fredericosachweh** [comment]
from rest_framework_bulk.routes import BulkRouter

from django.conf.urls import url, include

from screen.api.v1 import views

router = BulkRouter()
router.register(r'category', views.ScreenCategoryViewSet, 'category')
router.register(r'config', views.ScreenConfigViewSet, 'config')
router.register(r'modal', views.ModalViewSet, 'modal')
router.register(r'screen', views.ScreenViewSet, 'screen')
router.register(r'screen-modal-position', views.ScreenModalPositionViewSet, 'screen-modal-position')
router.register(r'screen-modal', views.ScreenModalViewSet, 'screen-modal')
urlpatterns = [
    url(r'', include(router.urls))
]

**Comment by miki725** [comment]
are you trying to use `ListBulkCreateUpdateDestroyAPIView` with a router?

**Comment by fredericosachweh** [comment]
Yes, Can't I?
If I can't use sorry.

**Comment by miki725** [comment]
Yes you cant. You can only use `ViewSet`s in routers which `APIView` is not. You can use the available mixins to add necessary functionality for viewsets.

closing
